### ISSUE TITLE
[UI] 바텀 내비게이션 수정

### ISSUE THREAD

**Issue by yys7517** [ParkChiUng/My_Ai_Tirp#13]
## 💡 Issue

메인화면 BottomNavigation 수정

## 📝 todo
- [x] 색상 Selector 
- [x] 메뉴 이름 변경
- [x] 메뉴 label 하드코딩 수정
- [x] RippleColor, Indicator 투명하게
