### ISSUE TITLE
[UI] 홈 화면 UI 구성

### ISSUE THREAD

**Issue by ParkChiUng** [ParkChiUng/My_Ai_Tirp#14]
## 💡 Issue

- UI 구성

## 📝 todo
- [ ] 검색 UI
- [ ] 인기 관광지 UI
- [ ] 지역 별 추천 관광지 UI
- [ ] 내 주변 관광지 UI
