### ISSUE TITLE
[UI] AI 추천 페이지 UI 구현

### ISSUE THREAD

**Issue by ParkChiUng** [ParkChiUng/My_Ai_Tirp#20]
## 💡 Issue

-  AI 추천 페이지 UI 구현

## 📝 todo
- [ ] 지역 선택 UI 구성
- [ ] 추천 여행지 해시태그 UI 구성 
- [ ] 여행지 리스트 리사이클러 뷰 UI 구성
