### ISSUE TITLE
[FEAT] 로그인, 회원가입 기능 구현

### ISSUE THREAD

**Issue by yys7517** [ParkChiUng/My_Ai_Tirp#27]
## 💡 Issue

- 자동 로그인
- Firebase Auth
- FireStore
- FireStorage
- DataStore

## 📝 todo
- [ ] Firebase Auth 연결
- [ ] 카카오 로그인 토큰, 회원번호 처리
- [ ] 자동 로그인을 위한 DataStore Client
