### ISSUE TITLE
[FEAT] 관광지 상세 페이지 구현

### ISSUE THREAD

**Issue by ParkChiUng** [ParkChiUng/My_Ai_Tirp#38]
## 💡 Issue

- 관광지 상세 페이지 UI  및 기능 구현
- FireBase 연동

## 📝 todo
- [x] 상세 페이지 UI 구현
- [x] 공유하기 기능 구현
- [x] 관광지 인기 리스트를 위한 FireBase 연동
