### ISSUE TITLE
[UI] 지도로 보기 화면 구성

### ISSUE THREAD

**Issue by yys7517** [ParkChiUng/My_Ai_Tirp#39]
## 💡 Issue

- 네이버 지도 MapView
- 현재 위치 버튼
- 지도 화면 진입시 초기 바텀시트 레이아웃
- 관광지 마커 클릭 시 나타나야할 바텀시트 레이아웃

## 📝 todo
- [x] 네이버 지도 MapView 
- [x] 현재 위치 버튼 
- [x] 지도 화면 진입시 초기 바텀시트 레이아웃
- [x] 관광지 마커 클릭 시 나타나야할 바텀시트 레이아웃
