### ISSUE TITLE
[FEAT] navigation component init

### ISSUE THREAD

**Issue by ParkChiUng** [ParkChiUng/My_Ai_Tirp#8]
## 💡 Issue

- 각 프레그먼트, xml  생성
- navigation graph 생성

## 📝 todo
- [ ] home.xml
- [ ] HomeFragment
- [ ] nearby_tours.xml
- [ ] NearbyToursFragment
- [ ] tours.xml
- [ ] ToursFragment
- [ ] ai_recommend.xml
- [ ] AIRecommendFragment
- [ ] tour_detail.xml
- [ ] TourDetailFragment
- [ ] user_detail.xml
- [ ] UserDetailFragment
- [ ] signup_profile.xml
- [ ] SignupProfileFragment
- [ ] diary.xml
- [ ] DiaryFragment
- [ ] search.xml
- [ ] SearchFragment
- [ ] tour_map.xml
- [ ] TourMapFragment
- [ ] liked_tours.xml
- [ ] LikedToursFragment
